name: Create and publish Container
on:
  push:
    tags:
      - '*'
jobs:
  run-npm-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: npm install and build
        run: |
          npm ci
          npm run build

  run-npm-test:
    runs-on: ubuntu-20.04
    needs: run-npm-build
    strategy:
      matrix:
        os: [ubuntu-20.04]
        node-version: [14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm ci, test and build
        run: |
          npm i -g jest
          npm t --if-present
          npm run build
        env:
          CI: true

  build-and-push-image:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    needs: run-npm-test
    steps:
    - name: create .env
      run: |
            echo DB_NAME=${{ secrets.DB_NAME }} >> .env
            echo DB_HOST=${{ secrets.DB_HOST }} >> .env
            echo DB_USER=${{ secrets.DB_USER }} >> .env
            echo DB_PASS=${{ secrets.DB_PASS }} >> .env

    - name: Checkout
      uses: actions/checkout@v2
    - name: Build container image
      uses: docker/build-push-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        repository: ${{ github.repository }}/testImage
        tag_with_sha: true
        tag_with_ref: true

